import type { AppState, Settings } from "../types";
import { DEFAULT_TRACKING_URLS } from "../lib/carriers";

export const DEFAULT_SETTINGS: Settings = {
  business: "",
  vatEnabled: false,
  legalStatus: "rien",
  country: "FR",
  vatNumber: "",
  vatRate: 20,
  marginScheme: true,
  threshold: 85000,
  address: "",
  email: "",
  phone: "",
  iban: "",
  footer: "",
  paymentTerms: 14,
  enabledModules: {
    clients: true,
    sav: true,
    facturation: true,
  },
  // Ordres de grandeur usuels ; chaque taux reste modifiable dans Facturation.
  platformFees: {
    Vinted: 0,
    "Vestiaire Collective": 15,
    Depop: 10,
    eBay: 12.8,
    Leboncoin: 0,
    Grailed: 9,
    Instagram: 0,
    WhatsApp: 0,
    "Main propre": 0,
    Boutique: 0,
    Autre: 0,
  },
  trackingUrls: { ...DEFAULT_TRACKING_URLS },
  nonSuppliers: [],
};

export const EMPTY_STATE: AppState = {
  items: [],
  todos: [],
  docs: [],
  returns: [],
  personalLitiges: [],
  expenses: [],
  suppliers: [],
  clients: [],
  requests: [],
  settings: DEFAULT_SETTINGS,
  seq: {},
  updatedAt: 0,
};

export const DEMO_STATE: AppState = {
  items: [
    // --- COLIS EN ARRIVAGE ---
    {
      id: "item-arr-1",
      name: "Dunk Low Retro Panda",
      brand: "Nike",
      type: "Sneakers",
      size: "42.5",
      source: "StockX Wholesale",
      supplierId: "sup-demo-1",
      quantity: 2,
      cost: 95,
      fees: 5,
      price: 155,
      platform: "",
      buyer: "",
      buyerUrl: "",
      saleFees: 0,
      shippingCost: 0,
      shippingPaid: 0,
      status: "arrivage",
      buyDate: "2026-09-10",
      receiveDate: "",
      saleDate: "",
      delivery: "commandee",
      notes: "Livraison groupée via Chronopost. Paires neuves avec boîte d'origine.",
      photoId: null,
      createdAt: Date.now() - 300000,
      carrier: "Chronopost",
      tracking: "139485729104FR",
      expectedDate: "2026-09-14",
      shipDate: "",
      shipping: "en_preparation",
      orderId: "CMD-2026-089",
      purchasePaid: true,
      lotTag: "LOT-NL-89",
      autoReceive: false,
    },
    {
      id: "item-arr-2",
      name: "Air Jordan 1 High OG Lost & Found",
      brand: "Jordan",
      type: "Sneakers",
      size: "43",
      source: "Vinted Pro",
      supplierId: "sup-demo-2",
      quantity: 1,
      cost: 170,
      fees: 10,
      price: 280,
      platform: "",
      buyer: "",
      buyerUrl: "",
      saleFees: 0,
      shippingCost: 0,
      shippingPaid: 0,
      status: "arrivage",
      buyDate: "2026-09-11",
      receiveDate: "",
      saleDate: "",
      delivery: "commandee",
      notes: "Très bon état, boîte d'origine légèrement abîmée.",
      photoId: null,
      createdAt: Date.now() - 250000,
      carrier: "Colissimo",
      tracking: "6A19283746501",
      expectedDate: "2026-09-15",
      shipDate: "",
      shipping: "en_preparation",
      orderId: "CMD-2026-092",
      purchasePaid: true,
      lotTag: "VINTED-L&F",
      autoReceive: false,
    },
    {
      id: "item-arr-3",
      name: "Box Logo Hoodie Heather Grey",
      brand: "Supreme",
      type: "Sweatshirt",
      size: "L",
      source: "Grossiste Supreme NL",
      supplierId: "sup-demo-3",
      quantity: 3,
      cost: 135,
      fees: 8,
      price: 240,
      platform: "",
      buyer: "",
      buyerUrl: "",
      saleFees: 0,
      shippingCost: 0,
      shippingPaid: 0,
      status: "arrivage",
      buyDate: "2026-09-09",
      receiveDate: "",
      saleDate: "",
      delivery: "commandee",
      notes: "Lot de 3 sweats neufs sous polybag d'origine.",
      photoId: null,
      createdAt: Date.now() - 200000,
      carrier: "DHL Express",
      tracking: "DHL-992018471",
      expectedDate: "2026-09-13",
      shipDate: "",
      shipping: "en_preparation",
      orderId: "CMD-2026-095",
      purchasePaid: true,
      lotTag: "BAC-ARRIVAGE-3",
      autoReceive: false,
    },
    {
      id: "item-arr-4",
      name: "Travis Scott x AJ1 Low Reverse Mocha",
      brand: "Jordan",
      type: "Sneakers",
      size: "41",
      source: "StockX Wholesale",
      supplierId: "sup-demo-1",
      quantity: 1,
      cost: 480,
      fees: 20,
      price: 890,
      platform: "",
      buyer: "",
      buyerUrl: "",
      saleFees: 0,
      shippingCost: 0,
      shippingPaid: 0,
      status: "arrivage",
      buyDate: "2026-09-12",
      receiveDate: "",
      saleDate: "",
      delivery: "commandee",
      notes: "Paire rare, vérification complémentaire à la réception conseillée.",
      photoId: null,
      createdAt: Date.now() - 150000,
      carrier: "Mondial Relay",
      tracking: "MR-88273641",
      expectedDate: "2026-09-16",
      shipDate: "",
      shipping: "en_preparation",
      orderId: "CMD-2026-098",
      purchasePaid: false,
      lotTag: "COFFRE-01",
      autoReceive: false,
    },

    // --- PRODUITS EN STOCK ---
    {
      id: "item-stk-1",
      name: "Kobe 6 Protro Reverse Grinch",
      brand: "Nike",
      type: "Sneakers",
      size: "44",
      source: "StockX Wholesale",
      supplierId: "sup-demo-1",
      quantity: 1,
      cost: 180,
      fees: 10,
      price: 350,
      platform: "",
      buyer: "",
      buyerUrl: "",
      saleFees: 0,
      shippingCost: 0,
      shippingPaid: 0,
      status: "stock",
      buyDate: "2026-08-25",
      receiveDate: "2026-08-29",
      saleDate: "",
      delivery: "livree",
      notes: "Stocké sous double box.",
      photoId: null,
      createdAt: Date.now() - 500000,
      carrier: "Chronopost",
      tracking: "",
      expectedDate: "",
      shipDate: "",
      shipping: "en_preparation",
      orderId: "CMD-2026-050",
      purchasePaid: true,
      lotTag: "BAC-A1",
      autoReceive: false,
    },
    {
      id: "item-stk-2",
      name: "Basic Zip Hoodie Black",
      brand: "Stüssy",
      type: "Sweatshirt",
      size: "M",
      source: "Vinted Pro",
      supplierId: "sup-demo-2",
      quantity: 1,
      cost: 55,
      fees: 5,
      price: 120,
      platform: "",
      buyer: "",
      buyerUrl: "",
      saleFees: 0,
      shippingCost: 0,
      shippingPaid: 0,
      status: "stock",
      buyDate: "2026-09-01",
      receiveDate: "2026-09-04",
      saleDate: "",
      delivery: "livree",
      notes: "État neuf avec étiquette.",
      photoId: null,
      createdAt: Date.now() - 450000,
      carrier: "",
      tracking: "",
      expectedDate: "",
      shipDate: "",
      shipping: "en_preparation",
      orderId: "",
      purchasePaid: true,
      lotTag: "PORTANT-02",
      autoReceive: false,
    },
    {
      id: "item-stk-3",
      name: "9060 Rain Cloud",
      brand: "New Balance",
      type: "Sneakers",
      size: "41.5",
      source: "Vinted Pro",
      supplierId: "sup-demo-2",
      quantity: 1,
      cost: 95,
      fees: 5,
      price: 175,
      platform: "",
      buyer: "",
      buyerUrl: "",
      saleFees: 0,
      shippingCost: 0,
      shippingPaid: 0,
      status: "stock",
      buyDate: "2026-08-30",
      receiveDate: "2026-09-02",
      saleDate: "",
      delivery: "livree",
      notes: "Modèle populaire très recherché sur Vinted.",
      photoId: null,
      createdAt: Date.now() - 400000,
      carrier: "",
      tracking: "",
      expectedDate: "",
      shipDate: "",
      shipping: "en_preparation",
      orderId: "",
      purchasePaid: true,
      lotTag: "ETAGERE-B1",
      autoReceive: false,
    },
    {
      id: "item-stk-4",
      name: "Beta LT Jacket Black",
      brand: "Arc'teryx",
      type: "Veste",
      size: "L",
      source: "Grossiste Supreme NL",
      supplierId: "sup-demo-3",
      quantity: 1,
      cost: 240,
      fees: 15,
      price: 430,
      platform: "",
      buyer: "",
      buyerUrl: "",
      saleFees: 0,
      shippingCost: 0,
      shippingPaid: 0,
      status: "stock",
      buyDate: "2026-08-20",
      receiveDate: "2026-08-24",
      saleDate: "",
      delivery: "livree",
      notes: "Gore-Tex authentifié avec étiquettes d'origine.",
      photoId: null,
      createdAt: Date.now() - 350000,
      carrier: "",
      tracking: "",
      expectedDate: "",
      shipDate: "",
      shipping: "en_preparation",
      orderId: "",
      purchasePaid: true,
      lotTag: "PORTANT-01",
      autoReceive: false,
    },
    {
      id: "item-stk-5",
      name: "Air Jordan 4 Metallic Red",
      brand: "Jordan",
      type: "Sneakers",
      size: "42",
      source: "StockX Wholesale",
      supplierId: "sup-demo-1",
      quantity: 1,
      cost: 210,
      fees: 10,
      price: 390,
      platform: "",
      buyer: "",
      buyerUrl: "",
      saleFees: 0,
      shippingCost: 0,
      shippingPaid: 0,
      status: "stock",
      buyDate: "2026-08-15",
      receiveDate: "2026-08-18",
      saleDate: "",
      delivery: "livree",
      notes: "Condition 10/10 Deadstock.",
      photoId: null,
      createdAt: Date.now() - 300000,
      carrier: "",
      tracking: "",
      expectedDate: "",
      shipDate: "",
      shipping: "en_preparation",
      orderId: "",
      purchasePaid: true,
      lotTag: "BAC-A2",
      autoReceive: false,
    },
    {
      id: "item-stk-6",
      name: "Double Knee Pant Canvas",
      brand: "Carhartt WIP",
      type: "Pantalon",
      size: "32/32",
      source: "Vinted Pro",
      supplierId: "sup-demo-2",
      quantity: 1,
      cost: 45,
      fees: 0,
      price: 95,
      platform: "",
      buyer: "",
      buyerUrl: "",
      saleFees: 0,
      shippingCost: 0,
      shippingPaid: 0,
      status: "stock",
      buyDate: "2026-09-05",
      receiveDate: "2026-09-06",
      saleDate: "",
      delivery: "livree",
      notes: "Couleur Hamilton Brown, coupe classique.",
      photoId: null,
      createdAt: Date.now() - 280000,
      carrier: "",
      tracking: "",
      expectedDate: "",
      shipDate: "",
      shipping: "en_preparation",
      orderId: "",
      purchasePaid: true,
      lotTag: "BAC-C1",
      autoReceive: false,
    },

    // --- ARTICLES VENDUS ---
    {
      id: "item-vd-1",
      name: "Dunk Low UNC",
      brand: "Nike",
      type: "Sneakers",
      size: "42",
      source: "Vinted Pro",
      supplierId: "sup-demo-2",
      quantity: 1,
      cost: 90,
      fees: 5,
      price: 210,
      platform: "Vinted",
      buyer: "Alexandre M.",
      clientId: "cli-demo-1",
      buyerUrl: "https://vinted.fr/member/alexandre_m",
      saleFees: 0,
      shippingCost: 0,
      shippingPaid: 0,
      status: "vendu",
      buyDate: "2026-08-10",
      receiveDate: "2026-08-14",
      saleDate: "2026-09-08",
      delivery: "livree",
      notes: "Vendu au prix fort sans négociation.",
      photoId: null,
      createdAt: Date.now() - 600000,
      carrier: "Mondial Relay",
      tracking: "MR-99281726",
      expectedDate: "",
      shipDate: "2026-09-09",
      shipping: "livree",
      orderId: "",
      purchasePaid: true,
      lotTag: "BAC-A1",
      autoReceive: false,
    },
    {
      id: "item-vd-2",
      name: "AJ1 Low Travis Scott Black Phantom",
      brand: "Jordan",
      type: "Sneakers",
      size: "43",
      source: "StockX Wholesale",
      supplierId: "sup-demo-1",
      quantity: 1,
      cost: 420,
      fees: 15,
      price: 790,
      platform: "Vestiaire Collective",
      buyer: "Sophie L.",
      clientId: "cli-demo-2",
      buyerUrl: "https://vestiairecollective.com/user/sophie_l",
      saleFees: 39,
      shippingCost: 10,
      shippingPaid: 0,
      status: "vendu",
      buyDate: "2026-08-05",
      receiveDate: "2026-08-10",
      saleDate: "2026-09-10",
      delivery: "livree",
      notes: "Vente conclue sur Vestiaire. Envoi en préparation.",
      photoId: null,
      createdAt: Date.now() - 700000,
      carrier: "Colissimo",
      tracking: "6A98172635142",
      expectedDate: "",
      shipDate: "2026-09-11",
      shipping: "en_preparation",
      orderId: "",
      purchasePaid: true,
      lotTag: "COFFRE-01",
      autoReceive: false,
    },
  ],
  todos: [
    {
      id: "todo-demo-1",
      text: "Scanner et contrôler le colis Chronopost (Dunk Panda)",
      col: "faire",
      order: 1,
      createdAt: Date.now() - 100000,
      itemId: "item-arr-1",
      supplierId: "sup-demo-1",
      supplierName: "StockX Wholesale",
      dueDate: "2026-09-14",
    },
    {
      id: "todo-demo-2",
      text: "Préparer l'envoi Vestiaire Collective pour Travis Scott Black Phantom",
      col: "envoyer",
      order: 2,
      createdAt: Date.now() - 90000,
      itemId: "item-vd-2",
      clientId: "cli-demo-2",
      clientName: "Sophie L.",
      dueDate: "2026-09-12",
    },
    {
      id: "todo-demo-3",
      text: "Relancer le grossiste NL pour la facture Supreme Box Logo",
      col: "acheter",
      order: 3,
      createdAt: Date.now() - 80000,
      supplierId: "sup-demo-3",
      supplierName: "Grossiste Supreme NL",
      dueDate: "2026-09-15",
    },
  ],
  docs: [],
  returns: [],
  personalLitiges: [],
  expenses: [
    {
      id: "exp-demo-1",
      label: "Cartons d'expédition & Film bulle (Lot 100)",
      category: "Emballage",
      amount: 48,
      date: "2026-09-01",
      amortizeMonths: 1,
      notes: "Commande Rajapack pour emballages de protection Vinted/Vestiaire.",
      createdAt: Date.now() - 400000,
    },
    {
      id: "exp-demo-2",
      label: "Imprimante Thermique Étiquettes Dymo",
      category: "Matériel",
      amount: 129,
      date: "2026-09-05",
      amortizeMonths: 12,
      notes: "Imprimante thermique pour bordereaux Colissimo & Mondial Relay.",
      createdAt: Date.now() - 300000,
    },
  ],
  suppliers: [
    {
      id: "sup-demo-1",
      name: "StockX Wholesale",
      contact: "Marc V.",
      email: "b2b@stockx.com",
      phone: "+33 6 12 34 56 78",
      url: "https://stockx.com",
      address: "Paris, France",
      terms: 14,
      rating: 5,
      notes: "Fournisseur B2B principal pour paires authentifiées et recherchées.",
      createdAt: Date.now() - 1000000,
    },
    {
      id: "sup-demo-2",
      name: "Vinted Pro",
      contact: "Thomas Resell",
      email: "thomas@vintedpro.fr",
      phone: "+33 6 98 76 54 32",
      url: "https://vinted.fr",
      address: "Lyon, France",
      terms: 7,
      rating: 4,
      notes: "Partenaire de confiance pour lots sneakers & streetwear d'occasion.",
      createdAt: Date.now() - 900000,
    },
    {
      id: "sup-demo-3",
      name: "Grossiste Supreme NL",
      contact: "Jan van Berg",
      email: "contact@supremenl.nl",
      phone: "+31 20 123 4567",
      url: "https://supremenl.nl",
      address: "Amsterdam, Pays-Bas",
      terms: 30,
      rating: 5,
      notes: "Spécialiste drops Supreme & Palace neufs scellés avec facture.",
      createdAt: Date.now() - 800000,
    },
  ],
  clients: [
    {
      id: "cli-demo-1",
      name: "Alexandre M.",
      email: "alexandre.m@gmail.com",
      phone: "+33 6 11 22 33 44",
      address: "12 Rue de la Paix, 75002 Paris",
      platform: "Vinted",
      profileUrl: "https://vinted.fr/member/alexandre_m",
      notes: "Acheteur régulier paires Nike taille 42/42.5. Paye rapidement.",
      createdAt: Date.now() - 900000,
    },
    {
      id: "cli-demo-2",
      name: "Sophie L.",
      email: "sophie.luxe@fashion.fr",
      phone: "+33 6 55 44 33 22",
      address: "8 Avenue Montaigne, 75008 Paris",
      platform: "Vestiaire Collective",
      profileUrl: "https://vestiairecollective.com/user/sophie_l",
      notes: "Cliente haut de gamme pour paires rares & éditions limitées.",
      createdAt: Date.now() - 800000,
    },
    {
      id: "cli-demo-3",
      name: "Julien B.",
      email: "julien.b@outlook.fr",
      phone: "+33 7 88 99 00 11",
      address: "45 Rue Nationale, 69002 Lyon",
      platform: "Instagram",
      profileUrl: "https://instagram.com/julien_kicks",
      notes: "Acheteur en direct via Instagram & WhatsApp, remise main propre Lyon.",
      createdAt: Date.now() - 700000,
    },
  ],
  requests: [],
  settings: DEFAULT_SETTINGS,
  seq: {},
  updatedAt: Date.now(),
};
